apiVersion: apps/v1
kind: Deployment
metadata:
  name: flytaxi-api
  namespace: flytaxi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flytaxi-api
  template:
    metadata:
      labels:
        app: flytaxi-api
    spec:
      containers:
        - name: api
          image: ivalexa111/flytaxi-api:latest
          env:
            - name: DB_URL
              value: postgres://flytaxi:flytaxi@postgres.flytaxi.svc.cluster.local:5432/flytaxi?sslmode=disable
            - name: HTTP_PORT
              value: "8080"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: flytaxi-secrets
                  key: jwt-secret
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: flytaxi
spec:
  selector:
    app: flytaxi-api
  ports:
    - port: 8080
      targetPort: 8080
