apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flytaxi-postgres-pvc
  namespace: flytaxi
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flytaxi-postgres
  namespace: flytaxi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flytaxi-postgres
  template:
    metadata:
      labels:
        app: flytaxi-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: flytaxi
            - name: POSTGRES_USER
              value: flytaxi
            - name: POSTGRES_PASSWORD
              value: flytaxi
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: flytaxi-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: flytaxi
spec:
  selector:
    app: flytaxi-postgres
  ports:
    - name: db
      port: 5432
      targetPort: 5432
